### ISSUE TITLE
Error in SCMapping when using "Circle" as shapeSpot

### ISSUE THREAD

**Issue by katimbach** [YingMa1993/CARD#10]
Hi, 

Thanks so much for making this excellent tool! So far it has been very straightforward to use and helpful to my analysis.

I however am experiencing a slight error when trying the single cell resolution mapping. I ran it with the default "Square" as mentioned in the example analysis, but I tried re-running using "Circle" (I am using Visium spatial data so I think this more accurately represents the spots in my case). This generates the following:
```
scMapping = CARD_SCMapping(CARD_obj,shapeSpot="Circle",numCell=7,ncore=n.cores)
Error in runifdisc(numCell, radius = min_distance, centre = c(Cords[i,  : 
  could not find function "runifdisc"
```

I tried installing the surveillance package, which from what I can tell is where runifdisc() originates, but to no avail unfortunately. Any insight on how I might resolve this?

**Comment by katimbach** [comment]
Sorry, I realize now this refers to the capture area itself and not the shape of the spots, my mistake!

**Comment by YingMa0107** [comment]
Hi @katimbach,

No worries at all! Thank you for reporting this! The runifdisc function does not work here was because the spatstat.random package was not imported properly. I have updated the code, now you should be able to run the function when shapeSpot="Circle". I also updated the tutorial to emphasize more about the interpretation of shapeSpot.

**Comment by katimbach** [comment]
Hi @YingMa0107 ,

Excellent, in that case I'm glad I could help!

I have a quick question regarding the development of the package- as it stands, as far as I can tell, it can only handle one capture area at a time due to the limitations imposed by the singular coordinate reference. In the future might there be plans to accommodate multiple capture areas in the same input? 

I ask because I am dealing with Visium samples that are iterative slices of tissues from the same slide/conditions, and I have subset them to process each individually, but I wonder if the additional spots in the input might improve the statistical power of deconvolution in some way? This multiple-capture capability is available in other deconvolution pipelines, such as Seurat's and Cell2location. I suppose I could artificially do this for now by generating a kind of Frankenstein spots/coordinates by adding the x coordinates iteratively for each capture, but I was just curious as to whether this has been considered on the developer end! So far this package has been excellent- very user friendly and straightforward.

**Comment by YingMa0107** [comment]
Hi @katimbach， 

Thank you very much for proposing this question! Good point! This might be a future direction in my next few projects. If you just want to simply try CARD, I agree with what you proposed that you can artificially generate coordinates to separate different slices together. For example, one way that I have tried before is: 

```
#### if you first have a combined slices coordinates data
for(islice in 1:NtotalSlices){
    if((islice %% 2) != 0){ ## odd slices 
   df$x[df$slice == islice] = 50*islice + df$x[df$slice == slice] ### you can modify the 50 here to be the maximum x coordinates among all slices 
}else if ((islice %% 2) == 0){ ## even slices 
       df$y[df$slice == islice] = 100*islice + df$y[df$slice == slice] ### you can modify the 100 here to be the maximum y coordinates among all slices 
}
}

```

In this way, the slices will be separated and each spatial location is unique, and the within-slice spatial relationship will not be affected. You can also plot the slices to see if this makes sense to you. Then you can put the combined count and the combined modified spatial coordinates into CARD (I haven't run it on a multiple-slice real dataset, but will try it later). Let me know if I understand your point correctly and let me know if you have further questions!

**Comment by katimbach** [comment]
Hi @YingMa0107,

Thanks for your advice! I actually ended up going ahead and doing something similar for my samples to adapt their coordinates and put them into a single CARD object, which fared well. Interestingly, when comparing the deconvolution proportions of a given capture's spots from the capture-only analysis vs that of the entire slide, the proportions changed slightly for some spots, but seemed to largely exhibit the same general pattern. I assume this is due to change in statistical power by using more spots in the combined slide object compared to each capture area independently, so I will maintain those estimates as the more statistically robust values.
