### ISSUE TITLE
question in deconvolution using CARDfree

### ISSUE THREAD

**Issue by LYNLLL** [YingMa1993/CARD#12]
When using a self defined markers of each celltype, the outcome of celltype label is changed. How can we infer the origin label of each renamed cell type?

**Comment by JoyOtten** [comment]
HI, can we reopen this one. I actually have a similar question with the names that I gave in in my marker gene list is completely changed to C1-5. However, if I put in the same order of names from the marker list that I had before the cell types do not match with what we know. It seems that there is some swapping going on. How could we trace back the names of the original marker gene list with the C1-X naming?
