### ISSUE TITLE
Error in Basis[, ict] : subscript out of bounds in CARD_deconvolution

### ISSUE THREAD

**Issue by Zjianglin** [YingMa1993/CARD#15]
Hi developer, I'm trying to use `CARD` to perform cell type deconvolution fro my spatial transcriptomics data. Howver, It crashed  out with 'Error in Basis[, ict] : subscript out of bounds' in CARD_deconvolution step.

Here is my data and steps:
```R
spatial_count <- ctrl3m_visium@assays$Spatial@counts
print(spatial_count[1:5, 1:4])
spatial_loc <- ctrl3m_visium@images$slice1@coordinates
spatial_loc <- spatial_loc[, c('imagerow', 'imagecol')]
colnames(spatial_loc) <- c('x', 'y')
head(spatial_loc)

sc_count <- scrna_x@assays$RNA@counts
sc_meta <- scrna_x@meta.data[, c('anno', 'anno2', 'sample')]
colnames(sc_meta) <- c('cellType1', 'cellType', 'sampleInfo')

> CARD_obj = createCARDObject(
+     sc_count = sc_count,
+     sc_meta = sc_meta,
+     spatial_count = spatial_count,
+     spatial_location = spatial_loc,
+     ct.varname = "cellType",
+     ct.select = unique(sc_meta$cellType),
+     sample.varname = "sampleInfo",
+     minCountGene = 10,
+     minCountSpot = 2) 
## QC on scRNASeq dataset! ...
## QC on spatially-resolved dataset! ...
> CARD_obj = CARD_deconvolution(CARD_object = CARD_obj)
## create reference matrix from scRNASeq...
## Select Informative Genes! ...
Error in Basis[, ict] : subscript out of bounds


####=============
> sc_eset = CARD_obj@sc_eset
> ct.varname = CARD_obj@info_parameters$ct.varname
> ct.select = CARD_obj@info_parameters$ct.select
> ##### check if the ct.select existing in the single cell RNAseq reference
> print(ct.select  %in% colData(sc_eset)[,ct.varname])
[1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE


> print(spatial_count[1:5, 1:4])
5 x 4 sparse Matrix of class "dgCMatrix"
        AAACAAGTATCTCCCA-1 AAACAATCTACTAGCA-1 AAACACCAATAACTGC-1 AAACAGAGCGACTCCT-1
Sox17                    1                  .                  .                  1
Mrpl15                   2                  .                  1                  2
Lypla1                   1                  1                  3                  .
Tcea1                    2                  1                  .                  .
Atp6v1h                  .                  .                  .                  .
> head(spatial_loc)
                       x     y
AAACAAGTATCTCCCA-1 13327  7211
AAACAATCTACTAGCA-1  7031 15977
AAACACCAATAACTGC-1  4441  5553
AAACAGAGCGACTCCT-1 12485 13917
AAACAGCTTTCAGAAG-1  3377  8535
AAACAGGGTCTATATT-1  3803  7789

> print(sc_count[1:4, 1:4])
4 x 4 sparse Matrix of class "dgCMatrix"
        AAACCTGAGAGGACGG-CN_3m AAACCTGAGAGTAAGG-CN_3m AAACCTGAGATAGCAT-CN_3m AAACCTGAGATGCCTT-CN_3m
Sox17                        .                      .                      .                      .
Gm37587                      .                      .                      .                      .
Mrpl15                       .                      .                      .                      1
Lypla1                       .                      1                      .                      1
> head(sc_meta)
                       cellType1  cellType sampleInfo
AAACCTGAGAGGACGG-CN_3m      Mast       Neu      CN_3m
AAACCTGAGAGTAAGG-CN_3m Monocytes Monocytes      CN_3m
AAACCTGAGATAGCAT-CN_3m       Neu       Neu      CN_3m
AAACCTGAGATGCCTT-CN_3m Monocytes Monocytes      CN_3m
AAACCTGAGCCCTAAT-CN_3m Monocytes Monocytes      CN_3m
AAACCTGAGGCACATG-CN_3m       Neu       Neu      CN_3m

```

Could you please hepl me? Thanks.

**Comment by chrismahony** [comment]
Hello

I have the same problem!

Here is what I ran:

CARD_obj = createCARDObject(
	sc_count = sc_count,
	sc_meta = sc_meta,
	spatial_count = spatial_count,
	spatial_location = coords,
	ct.varname = "cellType",
	ct.select = unique(sc_meta$cellType),
	sample.varname = "sampleInfo",
	minCountGene = 100,
	minCountSpot = 5) 


## QC on scRNASeq dataset! ...
## QC on spatially-resolved dataset! ...

CARD_obj = CARD_deconvolution(CARD_object = CARD_obj)

## create reference matrix from scRNASeq...
## Select Informative Genes! ...
Error in Basis[, ict] : subscript out of bounds


And here are some extra information:

head(sc_count)
6 x 29410 sparse Matrix of class "dgCMatrix"
   [[ suppressing 46 column names ‘S006_L1Q1_A03’, ‘S006_L1Q1_A05’, ‘S006_L1Q1_A07’ ... ]]
                                                                                                       
A1BG     . . . . . . . . . . . . . . 1 . . . . . . . . . . . . . . . . . .  .  .  .  . . . . . .  . . .
A1BG-AS1 . . . . . 1 . . . . . . . . . . . . 1 . . . 3 . . . . . . . . . .  .  .  .  . . . . . .  . . .
A1CF     . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  .  .  .  . . . . . .  . . .
A2M      . . . . 1 1 . 3 . . . 1 . . . 1 . . . . . . 1 . . . . . . . . 1 9 17 18 22 38 3 1 4 4 2 13 3 1
A2M-AS1  . 1 . . . 2 . . . . . . . . . . . . . . . . . . . . . . . . . . .  .  .  .  . 2 . . . .  . . .
A2ML1    . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .  .  .  .  . . . . . .  . . .
                 
A1BG     . ......
A1BG-AS1 . ......
A1CF     . ......
A2M      6 ......
A2M-AS1  . ......
A2ML1    . ......

 .....suppressing 29364 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................


head(sc_meta)
                     cellID cellType sampleInfo
S006_L1Q1_A03 S006_L1Q1_A03   T cell        amp
S006_L1Q1_A05 S006_L1Q1_A05   T cell        amp
S006_L1Q1_A07 S006_L1Q1_A07   T cell        amp
S006_L1Q1_A09 S006_L1Q1_A09   T cell        amp
S006_L1Q1_A11 S006_L1Q1_A11   T cell        amp
S006_L1Q1_A13 S006_L1Q1_A13   T cell        amp

head(spatial_count)
6 x 34170 sparse Matrix of class "dgCMatrix"
   [[ suppressing 46 column names ‘AAACACCAATAACTGC-1_1’, ‘AAACAGAGCGACTCCT-1_1’, ‘AAACCACTACACAGAT-1_1’ ... ]]
                                                                                                       
MIR1302-2HG . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
FAM138A     . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
OR4F5       . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.1  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.3  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
AL627309.2  . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .
                  
MIR1302-2HG ......
FAM138A     ......
OR4F5       ......
AL627309.1  ......
AL627309.3  ......
AL627309.2  ......

 .....suppressing 34124 columns in show(); maybe adjust 'options(max.print= *, width = *)'
 ..............................



head(coords)
                     xcoord ycoord
AAACACCAATAACTGC-1_1   5757   1706
AAACAGAGCGACTCCT-1_1   2154   5117
AAACCACTACACAGAT-1_1   1272   6165
AAACCGGGTAGGTACC-1_1   4401   2110
AAACCTCATGAAGTTG-1_1   4006   1696
AAACGACAGTCTTGCC-1_1   1192   6210


Any help would be greatly appreciated, thanks,
Chris

**Comment by YingMa0107** [comment]
Hi @Zjianglin and @chrismahony, 

Thank you for providing those details! There might be something wrong in the reference basis matrix or some mismatch happening here. Could you please try to run the following code and provide the output for me? 

```
##### code starts
library(CARD)
ct.select = CARD_object@info_parameters$ct.select
print(ct.select)
ct.varname = CARD_object@info_parameters$ct.varname
sample.varname = CARD_object@info_parameters$sample.varname
cat(paste0("## create reference matrix from scRNASeq...\n"))
sc_eset = CARD_object@sc_eset
Basis_ref = createscRef(sc_eset, ct.select, ct.varname, sample.varname)
Basis = Basis_ref$basis
print(colnames(Basis))
Basis = Basis[,colnames(Basis) %in% ct.select]
Basis = Basis[,match(ct.select,colnames(Basis))]
print(head(Basis))
spatial_count = CARD_object@spatial_countMat
commonGene = intersect(rownames(spatial_count),rownames(Basis))
print(head(commonGene))
##### code ends
```

Thanks! 

Best,
Ying

**Comment by chrismahony** [comment]
Thanks for the reply. here you go:

ct.select = CARD_obj@info_parameters$ct.select
> print(ct.select)
[1] "T cell"            "Monocyte"          "linning"           "Fibroblast"       
[5] "B cell"            "Endothelial cells" NA      

ct.varname = CARD_obj@info_parameters$ct.varname
> sample.varname = CARD_obj@info_parameters$sample.varname
> cat(paste0("## create reference matrix from scRNASeq...\n"))
## create reference matrix from scRNASeq...
> sc_eset = CARD_obj@sc_eset
> Basis_ref = createscRef(sc_eset, ct.select, ct.varname, sample.varname)
> Basis = Basis_ref$basis
> print(colnames(Basis))
[1] "T cell"            "Monocyte"          "linning"           "Fibroblast"       
[5] "B cell"            "Endothelial cells" NA         

Basis = Basis[,colnames(Basis) %in% ct.select]
> Basis = Basis[,match(ct.select,colnames(Basis))]
> print(head(Basis))
              T cell    Monocyte     linning  Fibroblast      B cell Endothelial cells <NA>
A1BG     0.009758364 0.007125891 0.008379888 0.568078350 0.006896552       0.184615385   NA
A1BG-AS1 0.069237918 0.093428345 0.036312849 0.062395663 0.109578544       0.020512821   NA
A1CF     0.013940520 0.018210610 0.016759777 0.008279169 0.026819923       0.000000000   NA
A2M      0.199814126 3.307996833 0.234636872 0.309114404 0.121839080       0.578205128   NA
A2M-AS1  0.303903346 0.061757720 0.094972067 0.036495872 0.043678161       0.001282051   NA
A2ML1    0.007434944 0.022961203 0.027932961 0.009928963 0.015325670       0.001282051   NA


spatial_count = CARD_obj@spatial_countMat
> commonGene = intersect(rownames(spatial_count),rownames(Basis))
> print(head(commonGene))
[1] "AL627309.1" "AP006222.2" "FAM87B"     "LINC00115"  "FAM41C"     "SAMD11"

**Comment by YingMa0107** [comment]
Hi @chrismahony, 

Thank you for your prompt reply! As you see, there is NA in the ct.select as well as the column names in the Basis matrix. I did add NA remove check inside the function of CARD package, but it seems that it doe not help here. So I will add more NA checking in the code, and also if you want to run the current package, you can just simply remove the NA cells in the scRNAseq data or rename it as "Unknown" if it does have expression in the scRNAseq count. 

Hope this helps!

**Comment by chrismahony** [comment]
COuld you help on the best way to do this?

I dont have NAs in my input data. If I try this:

CARD_obj@info_parameters$ct.select<-na.omit(CARD_obj@info_parameters$ct.select)

I get:

> ct.select = CARD_obj@info_parameters$ct.select
> print(ct.select)
[1] "T cell"            "Monocyte"          "linning"           "Fibroblast"        "B cell"            "Endothelial cells"
attr(,"na.action")
[1] 7
attr(,"class")
[1] "omit"

Thanks
Chris

**Comment by YingMa0107** [comment]
Hi @chrismahony, 

That is weird since ct.select stored in the CARD_obj@info_parameters$ct.select directly come from your input argument, could you please check the print(unique(sc_meta$cellType))? 

I've added one line to remove the NA in the ct.select in the package. Please reinstall the package and try your code again. Let me know if it does not work!

Thank you for your patience!

Best,
Ying

**Comment by chrismahony** [comment]
print(unique(sc_meta$cellType))
[1] "T cell"            "Monocyte"          "linning"           "Fibroblast"        "B cell"            "Endothelial cells"
[7] NA  

Which is strange when I run:

table(sc_meta$cellType)
 B cell Endothelial cells        Fibroblast           linning          Monocyte            T cell 
             1305               780             23548               358              1263              2152 

Where is the NA coming from?

Thanks
Chris

**Comment by YingMa0107** [comment]
Hi @chrismahony 

The table() function in R does not print NA values by default, you have to specify the useNA = "ifany". for example, 

```
a = c(NA,1,1,1,2,2,2)
##### the results do not contain NA counts
print(table(a))
##### the results contain NA counts
print(table(a,useNA = "ifany"))

```
Best, 
Ying

**Comment by Zjianglin** [comment]
Hi @YingMa0107 , I tried to run the code and get outputs below:

```R
> ct.select = CARD_obj@info_parameters$ct.select
> print(ct.select)
[1] Neu       Monocytes T_Cd8     T_Cd4     NK        DCs       Bcell     LSECs     Mast     
Levels: T_Cd4 Bcell Monocytes LSECs Neu NK DCs Hep T_Cd8 Mast
> ct.varname = CARD_obj@info_parameters$ct.varname
> sample.varname = CARD_obj@info_parameters$sample.varname
> cat(paste0("## create reference matrix from scRNASeq...\n"))
## create reference matrix from scRNASeq...
> sc_eset = CARD_obj@sc_eset
> Basis_ref = createscRef(sc_eset, ct.select, ct.varname, sample.varname)
> Basis = Basis_ref$basis
> print(colnames(Basis))
[1] "Neu"       "Monocytes" "T_Cd8"     "T_Cd4"     "NK"        "DCs"       "Bcell"     "LSECs"     "Mast"     
> Basis = Basis[,colnames(Basis) %in% ct.select]
> Basis = Basis[,match(ct.select,colnames(Basis))]
> print(head(Basis))
               Neu   Monocytes      T_Cd8      T_Cd4        NK       DCs      Bcell     LSECs       Mast
Sox17   0.00000000 0.001123776 0.00000000 0.00000000 0.0000000 0.0000000 0.00000000 0.4047619 0.00000000
Mrpl15  0.02207063 0.565419811 0.27124183 0.30563798 0.2824427 0.4386617 0.26984127 0.2380952 0.32692308
Lypla1  0.12038523 0.486916038 0.14052288 0.14540059 0.1374046 0.2379182 0.07936508 0.2857143 0.13461538
Tcea1   0.15609952 1.121046717 0.57843137 0.58160237 0.5152672 0.9293680 0.47619048 1.2857143 0.55769231
Atp6v1h 0.07624398 0.390110772 0.09150327 0.09495549 0.1221374 0.3011152 0.07936508 0.1904762 0.09615385
Rb1cc1  0.54654896 0.532509231 0.20588235 0.18100890 0.2404580 0.3011152 0.15873016 0.6428571 0.53846154
> spatial_count = CARD_obj@spatial_countMat
> commonGene = intersect(rownames(spatial_count),rownames(Basis))
> print(head(commonGene))
[1] "Sox17"   "Mrpl15"  "Lypla1"  "Tcea1"   "Atp6v1h" "Rb1cc1" 
> ##### code ends

> table(ct.select)
ct.select
    T_Cd4     Bcell Monocytes     LSECs       Neu        NK       DCs       Hep     T_Cd8      Mast 
        1         1         1         1         1         1         1         0         1         1 
> table(ct.select, useNA='ifany')
ct.select
    T_Cd4     Bcell Monocytes     LSECs       Neu        NK       DCs       Hep     T_Cd8      Mast 
        1         1         1         1         1         1         1         0         1         1 
```

It seems no `NA` in my cell types, what whould I do next? thank you.

**Comment by chrismahony** [comment]
I have re-installed and re ran:
CARD_obj = createCARDObject(
	sc_count = sc_count,
	sc_meta = sc_meta,
	spatial_count = spatial_count,
	spatial_location = coords,
	ct.varname = "cellType",
	ct.select = unique(sc_meta$cellType),
	sample.varname = "sampleInfo",
	minCountGene = 100,
	minCountSpot = 5) 


But now I get:

## QC on scRNASeq dataset! ...
## QC on spatially-resolved dataset! ...
Error in createCARDObject(sc_count = sc_count, sc_meta = sc_meta, spatial_count = spatial_count, : The number of spatial locations in spatial_count and spatial_location should be consistent! (spatial_count -- p x n; spatial_location -- n x 2)

If you could help, that would be great, thanks,
Chris

**Comment by YingMa0107** [comment]
Hi @Zjianglin, 

Based on your output, when you table(ct.select), the "Hep" seem to be 0, could you please check the following to see what's going on in the "Hep" cells?

```
library(SingleCellExperiment)
library(CARD)
ct.select = CARD_object@info_parameters$ct.select
print(ct.select)
ct.varname = CARD_object@info_parameters$ct.varname
sample.varname = CARD_object@info_parameters$sample.varname 
sc_eset = CARD_object@sc_eset
print(unique(colData(sc_eset)[,ct.varname])) ### check if there are NA cells in your sc_eset 


```

Also please double check your input data of the sc_meta to check the "Hep" cells! Maybe run the following: 

`table(sc_meta$cellType,useNA = "ifany")`

Thanks!

**Comment by YingMa0107** [comment]
Hi @chrismahony,

Thanks for the description. Based on your output, it seems that your input data is not correct, the error message says: The number of spatial locations in spatial_count and spatial_location should be consistent! so basically, when ncol(spatial_count) != nrow(coords) it will pop out this error message. Please double check the dimension of the spatial count matrix and spatial location data. 
Thanks!

Best,
Ying

**Comment by chrismahony** [comment]
Thanks, it seems to have worked, my code is below with a f extra lines included:

colnames(sc_count)[!(colnames(sc_count) %in% row.names(sc_meta))]
sc_count<-sc_count[,colnames(sc_count)!="CTCCATGCATTGCTGA_mm3"]
sc_count<-sc_count[,colnames(sc_count)!="GACATCAAGTGATAAC_mm3"]
sc_count<-sc_count[,colnames(sc_count)!="GCCAACGAGACACACG_mm3"]
sc_count<-sc_count[,colnames(sc_count)!="GCTGAATTCGCACTCT_mm3"]
ncol(sc_count)

nrow(coords)!=ncol(spatial_count)
coords <- coords[colnames(spatial_count),]
nrow(coords)
ncol(spatial_count)

colnames(coords) <- c('x','y')

CARD_obj = createCARDObject(
	sc_count = sc_count,
	sc_meta = sc_meta,
	spatial_count = spatial_count,
	spatial_location = coords,
	ct.varname = "cellType",
	ct.select = unique(sc_meta$cellType),
	sample.varname = "sampleInfo",
	minCountGene = 100,
	minCountSpot = 5) 

CARD_obj = CARD_deconvolution(CARD_object = CARD_obj)

**Comment by chrismahony** [comment]
Can you help with a follow on problem?

I have run the follwing:

#create CARD object for one slide (#mergin is my Seurat object)
Slide1SampleA <- merging[,grepl("Slide1SampleA", merging$orig.ident, ignore.case=TRUE)]
spatial_countS1A<-Slide1SampleA@assays[["Spatial"]]@counts

spatial_countS1A<-as.data.frame(spatial_countS1A)
spatial_countS1A<-t(spatial_countS1A)
spatial_countS1A<-as.data.frame(spatial_countS1A)

coords_df<-as.data.frame(coords)

coordsS1A <- coords_df[(rownames(coords_df) %in% rownames(spatial_countS1A)),]

spatial_countS1A<-Slide1SampleA@assays[["Spatial"]]@counts

colnames(spatial_countS1A)[!(colnames(spatial_countS1A) %in% row.names(coordsS1A))]

spatial_countS1A<-spatial_countS1A[,colnames(spatial_countS1A)!="TCGTGTACTATGGATG-1_1"]
spatial_countS1A<-spatial_countS1A[,colnames(spatial_countS1A)!="TTGTTCTAGATACGCT-1_1"]

CARD_objS1A = createCARDObject(
	sc_count = sc_count,
	sc_meta = sc_meta,
	spatial_count = spatial_countS1A,
	spatial_location = coordsS1A,
	ct.varname = "cellType",
	ct.select = unique(sc_meta$cellType),
	sample.varname = "sampleInfo",
	minCountGene = 100,
	minCountSpot = 5) 

CARD_objS1A = CARD_deconvolution(CARD_object = CARD_objS1A)

print(CARD_objS1A@Proportion_CARD[1:2,])

colors = c("#FFD92F","#4DAF4A","#FCCDE5","#D9D9D9","#377EB8","#7FC97F")
p1 <- CARD.visualize.pie(proportion = CARD_objS1A@Proportion_CARD,spatial_location = CARD_objS1A@spatial_location, colors = colors)
print(p1)

But When I run print(p1) I have an empty graphic with no pie charts/cells. Could you help?

Thanks
Chris

**Comment by YingMa0107** [comment]
Hi @chrismahony, 

Could you please check the proportion matrix to see if there are output first? 

```
print(head(CARD_objS1A@Proportion_CARD))
print(dim(CARD_objS1A@Proportion_CARD))
print(head(CARD_objS1A@spatial_location))
```
How many spatial locations do you have? I've previously mentioned in the tutorial that if the number of spots > 500, we recommend the users to visualize the proportion directly instead of the pie plot as the pie will be tiny in the scatterpie plot when there are a lot of spots. 

Have you tried other plot functions like CARD.visualize.prop() to see if there are output? 



Thanks!

**Comment by chrismahony** [comment]
print(head(CARD_objS1A@Proportion_CARD))
                           T cell   Monocyte      linning Fibroblast
AAACACCAATAACTGC-1_1 0.0021607285 0.03887749 2.479007e-07 0.05016506
AAACAGAGCGACTCCT-1_1 0.0131602299 0.33293546 4.347025e-06 0.11348994
AAACCACTACACAGAT-1_1 0.0049745151 0.37825911 5.238613e-04 0.28710005
AAACCGGGTAGGTACC-1_1 0.0004795838 0.20576607 6.468465e-09 0.16327588
AAACCTCATGAAGTTG-1_1 0.0002662111 0.16988369 2.614192e-08 0.14000853
AAACGACAGTCTTGCC-1_1 0.0099489963 0.38056735 4.489544e-04 0.24612170
                          B cell Endothelial cells
AAACACCAATAACTGC-1_1 0.029026747         0.8797697
AAACAGAGCGACTCCT-1_1 0.043337798         0.4970722
AAACCACTACACAGAT-1_1 0.008524175         0.3206183
AAACCGGGTAGGTACC-1_1 0.061741462         0.5687370
AAACCTCATGAAGTTG-1_1 0.055158588         0.6346830
AAACGACAGTCTTGCC-1_1 0.043548782         0.3193642

print(dim(CARD_objS1A@Proportion_CARD))
[1] 1395    6

print(head(CARD_objS1A@spatial_location))
                        x    y
AAACACCAATAACTGC-1_1 5757 1706
AAACAGAGCGACTCCT-1_1 2154 5117
AAACCACTACACAGAT-1_1 1272 6165
AAACCGGGTAGGTACC-1_1 4401 2110
AAACCTCATGAAGTTG-1_1 4006 1696
AAACGACAGTCTTGCC-1_1 1192 6210

Yes I have >500, I have 1370, so this could be the problem. CARD.visualize.prop() works OK. Thanks!

**Comment by Zjianglin** [comment]
Hi @YingMa0107, thanks for your help. After reload the scRNA-seq dataset with full celltypes, It works now. Thank you~

**Comment by Zjianglin** [comment]
Hi @YingMa0107 , I have another problem. Although it woks normally now, I cannot see the cell type proption figure, it seems to be a blank. Could you please help me?
```
> CARD_obj = CARD_deconvolution(CARD_object = CARD_obj)
## create reference matrix from scRNASeq...
## Select Informative Genes! ...
## Deconvolution Starts! ...
## Deconvolution Finish! ...
> print(CARD_obj@Proportion_CARD[1:2,])
                         Macro       Neu       Hep     Tcell           NK           DC        Bcell      LSECs         Mast
AAACAAGTATCTCCCA-1 1.73168e-04 0.1252344 0.5173939 0.3093866 1.228468e-11 0.0004270752 1.023716e-12 0.04738485 2.181749e-18
AAACAATCTACTAGCA-1 7.24718e-05 0.1612614 0.5191890 0.2611384 5.266997e-12 0.0025369750 1.154096e-12 0.05580181 1.769564e-18
> summary(CARD_obj@Proportion_CARD)
     Macro                Neu                 Hep             Tcell              NK                  DC           
 Min.   :0.000e+00   Min.   :0.0001082   Min.   :0.1025   Min.   :0.1788   Min.   :0.000e+00   Min.   :0.0000000  
 1st Qu.:1.486e-05   1st Qu.:0.0845727   1st Qu.:0.4445   1st Qu.:0.3056   1st Qu.:0.000e+00   1st Qu.:0.0008425  
 Median :7.028e-05   Median :0.1219434   Median :0.4863   Median :0.3291   Median :0.000e+00   Median :0.0049635  
 Mean   :7.789e-04   Mean   :0.1288002   Mean   :0.4799   Mean   :0.3296   Mean   :1.184e-05   Mean   :0.0114700  
 3rd Qu.:3.438e-04   3rd Qu.:0.1657418   3rd Qu.:0.5230   3rd Qu.:0.3528   3rd Qu.:1.000e-09   3rd Qu.:0.0159511  
 Max.   :1.039e-01   Max.   :0.5354555   Max.   :0.6930   Max.   :0.7002   Max.   :2.262e-02   Max.   :0.1674103  
     Bcell               LSECs                Mast          
 Min.   :0.000e+00   Min.   :0.0008039   Min.   :0.000e+00  
 1st Qu.:0.000e+00   1st Qu.:0.0368691   1st Qu.:0.000e+00  
 Median :0.000e+00   Median :0.0482667   Median :0.000e+00  
 Mean   :5.386e-05   Mean   :0.0493721   Mean   :1.012e-08  
 3rd Qu.:0.000e+00   3rd Qu.:0.0602907   3rd Qu.:0.000e+00  
 Max.   :1.605e-01   Max.   :0.1555639   Max.   :3.053e-05  
> colors = c("#FFD92F","#4DAF4A","#FCCDE5","#D9D9D9","#377EB8","#7FC97F","#BEAED4",
+            "#FDC086","#FFFF99","#386CB0","#F0027F","#BF5B17","#666666","#1B9E77","#D95F02",
+            "#7570B3","#E7298A","#66A61E","#E6AB02","#A6761D")
> colors <- colors[1:length(unique(ct.select))]
> p1 <- CARD.visualize.pie(proportion = CARD_obj@Proportion_CARD,spatial_location = CARD_obj@spatial_location, colors = colors)
> print(p1)
#below is the output.
```
![Cell type proption](https://user-images.githubusercontent.com/14870842/178761155-1949dbb0-2c78-4d61-b65f-4039e5d87469.png)

Menawhile, I can select some interested cell types to visualize separately.
```
> p2 <- CARD.visualize.prop(
+     proportion = CARD_obj@Proportion_CARD,        
+     spatial_location = CARD_obj@spatial_location, 
+     ct.visualize = ct.visualize,                 ### selected cell types to visualize
+     colors = c("lightblue","lightyellow","red"), ### if not provide, we will use the default colors
+     NumCols = 4)                                 ### number of columns in the figure panel
> print(p2)
```

![separate cell type visualization](https://user-images.githubusercontent.com/14870842/178762792-789a8fa6-02d0-4411-bc3a-485a247af497.png)

**Comment by YingMa0107** [comment]
Hi @Zjianglin, 

As you see my previous answer in the post (also mentioned in the tutorial) that we do not recommend users to use the scatterpie plot for the data with spot > 500 as the pie will be tiny (almost nothing) in the scatterpie plot when there are a lot of spots. Moreover, when you use CARD.visualize.prop() function, you can print out the figure using png()or pdf() by specifying the height and width of the figure, then the point will look normal in the png or pdf figure. 

Thanks!

**Comment by juliaryann** [comment]
@YingMa0107 ,
On the topic of datasets that are too large to create the pie-chart figure, is there a way to instead create a text file of the data in those pie charts, maybe a table of the percent of each cell-type at each spot?
Thank you,
Julia

**Comment by YingMa0107** [comment]
Hi @juliaryann,

Thank you for your suggestion! If you want the table, it can be extracted from the CARD object: `print(CARD_obj@Proportion_CARD)`

It is a N by K matrix, you can write it out as a table by 

`write.table(CARD_obj@Proportion_CARD,file = "CARD_prop.txt")`

Thanks!

Best,
Ying
