### ISSUE TITLE
Library won't install

### ISSUE THREAD

**Issue by PIR015** [YingMa1993/CARD#16]
Hi all, I was trying to give this deconvolution tool a go, however I won't install for some reason. This is the error I get: 

> library(CARD)
Error: package or namespace load failed for ‘CARD’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 namespace ‘spatstat.utils’ 2.1-0 is already loaded, but >= 2.2.0 is required
In addition: Warning message:
replacing previous import ‘RcppML::nmf’ by ‘NMF::nmf’ when loading ‘CARD’ 

Thank you.

**Comment by YingMa0107** [comment]
Hi @PIR015, 

Thank you for your interest in our method! Could you please try to reinstall the package "spatstat.utils"? If it does not solve the problem, could you please provide the sessionInfo() information in R for me to have a look at what's going on? 

Thank you! 


Best,
Ying
