### ISSUE TITLE
Recursive default argument in CARD.visualize.pie (colors=colors)

### ISSUE THREAD

**Issue by serenolopezdarwin** [YingMa1993/CARD#23]
If you don't provide a "colors" argument to CARD.visualize.pie, it throws the error:
`promise already under evaluation: recursive default argument reference or earlier problems?`

This is (usually) due to the argument being named the same thing as the default it is passed. Renaming either the argument or the object to something other than "colors" will fix it.

**Comment by YingMa0107** [comment]
Hi @serenolopezdarwin, 

Thank you very much for pointing out this bug! I just modified the code, now it should work when you don't provide the "colors" argument.

**Comment by Blackshoots** [comment]
Sorry but it still throws out the error:
> Error in CARD.visualize.pie(df, spatial_location) : 
>  promise already under evaluation: recursive default argument reference or earlier problems?
where the head of df is 
![image](https://user-images.githubusercontent.com/42287812/190450790-11e97211-f2a4-484e-b388-8ef09ee5b600.png)
and the head of spatial_location is
![image](https://user-images.githubusercontent.com/42287812/190451308-84bcc14e-0730-477c-a2a2-38a0a7318d9f.png)

**Comment by YingMa0107** [comment]
Hi @serenolopezdarwin, 

Thank you for reporting! 
Have you re-installed the updated CARD package? 
Have you tried the tutorial when not proving the colors successfully? I just tried it on my computer, and I can generate the pie plot without providing the colors. 

`p1 <- CARD.visualize.pie(proportion = CARD_obj@Proportion_CARD,spatial_location = CARD_obj@spatial_location)`
