### ISSUE TITLE
There existing selected genes that are not in the expression data!

### ISSUE THREAD

**Issue by Kaixin-Huang** [YingMa1993/CARD#28]
Dear Developers,

When I'm trying to visualize one of my interested genes using card in refined resolution, I kept coming to this error:

CARD.visualize.gene(
  spatial_expression = naive.card@spatial_countMat,
  spatial_location = naive.card@spatial_location,
  gene.visualize = c("Penk"),
  colors = NULL,
  NumCols = 1)

Error in CARD.visualize.gene(spatial_expression = naive.card@refined_expression,  : 
  There existing selected genes that are not in the expression data!

Then I found:
In CARD.obj@spatial_countMat, the number of genes is 10180
In CARD.obj@refined_expression, the number of genes is only 2330.

It seems that, when running CARD.imputation; the refined_expression matrix only use a small part of the whole expression matrix.

So how can I visualize my interested in a refined resolution, if it is not pressented in a refined resoluztion ?

Best Regards,
Huang

**Comment by diyang1354** [comment]
Same issue here, some genes are lost after imputation
