### ISSUE TITLE
install error (dependent packages)

### ISSUE THREAD

**Issue by gancao** [YingMa1993/CARD#3]
CARD.o: file not recognized: file format not recognized

**Comment by YingMa0107** [comment]
Hi @gancao, 

Thank you for your interest in our package! Could you please provide me more details for me to debug? For example,  
1) what is your operating system you used that show this error? 
2) and also what is the sessionInfo() output in R. 

Thanks!

**Comment by gancao** [comment]
I met the following errors, could you please provide units package for me?
installing to /tmp/RtmpMxxNof/Rinst26c8cd8b8810/00LOCK-CARD/00new/CARD/libs
   ** R
   ** data
   ** byte-compile and prepare package for lazy loading
   Error in library.dynam(lib, package, package.lib) :
     共享目标对象‘units.so’不存在
   Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace -> library.dynam
   停止执行
   ERROR: lazy loading failed for package ‘CARD’
─  removing ‘/tmp/RtmpMxxNof/Rinst26c8cd8b8810/CARD’
         -----------------------------------
   ERROR: package installation failed
错误: Failed to install 'CARD' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed


> sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=zh_CN.UTF_8       LC_NUMERIC=C
 [3] LC_TIME=zh_CN.UTF_8        LC_COLLATE=zh_CN.UTF_8
 [5] LC_MONETARY=zh_CN.UTF_8    LC_MESSAGES=zh_CN.UTF_8
 [7] LC_PAPER=zh_CN.UTF_8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF_8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
 [1] ps_1.6.0          prettyunits_1.1.1 rprojroot_2.0.2   crayon_1.4.2
 [5] withr_2.4.3       R6_2.5.1          lifecycle_1.0.1   magrittr_2.0.1
 [9] rlang_0.4.12      cachem_1.0.6      cli_3.1.0         curl_4.3.2
[13] remotes_2.4.2     fs_1.5.2          testthat_3.1.1    callr_3.7.0
[17] ellipsis_0.3.2    desc_1.4.0        devtools_2.4.3    tools_4.1.2
[21] glue_1.6.0        purrr_0.3.4       pkgload_1.2.4     fastmap_1.1.0
[25] compiler_4.1.2    processx_3.5.2    pkgbuild_1.3.1    sessioninfo_1.2.2
[29] memoise_2.0.1     usethis_2.1.5

**Comment by YingMa0107** [comment]
Hi @gancao, 

Thank you for the detailed output. I presume that there are something wrong with the sf package or you were not able to install it successfully. The units package is required by the sf package which was required by CARD (for the resolution enhancement purpose). Details see the post there [https://github.com/r-spatial/sf/issues/1937](https://github.com/r-spatial/sf/issues/1937). 

So could you please install the units package directly from CRAN (It should be easy to install!) and also the sf package? Then units.so will be in the "/units/libs/" folder after you installed it from CRAN. For example, 

```
install.packages("units")
```
****** details of installation of the sf package
[https://github.com/r-spatial/sf](https://github.com/r-spatial/sf)

**Comment by gancao** [comment]
When I used install.packages("units") to install the package, but it failed. I have tried many ways but I couldn't find the key reason. So could you please provide the packaged units package for me?
4.1.2/lib/R/library/utils/libs/utils.sosh: 行 1: 162068 已放弃               (吐核)R_TESTS= '/opt/R/4.1.2/lib/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/Rtmp1F8dRH/file275f7134a038b'
ERROR: loading failed
* removing ‘/home/ganrui/R/x86_64-pc-linux-gnu-library/4.1/units’
* restoring previous ‘/home/ganrui/R/x86_64-pc-linux-gnu-library/4.1/units’

The downloaded source packages are in
        ‘/tmp/RtmpRxLfgP/downloaded_packages’
Warning message:
In install.packages("units") :
  installation of package ‘units’ had non-zero exit status

**Comment by gancao** [comment]
When I used install.packages("units") to install the package, but it failed. I have tried many ways but I couldn't find the key reason. So could you please provide the packaged units package for me?
4.1.2/lib/R/library/utils/libs/utils.sosh: 行 1: 162068 已放弃 (吐核)R_TESTS= '/4.1.2/lib/R/bin/R' --no-save --no-restore --no-echo 2>&1 < '/tmp/Rtmp1F8dRH/file275f7134a038b'
ERROR: loading failed

The downloaded source packages are in
‘/tmp/RtmpRxLfgP/downloaded_packages’
Warning message:
In install.packages("units") :
installation of package ‘units’ had non-zero exit status
