### ISSUE TITLE
Rcpp function CARDfree() can not produce results.

### ISSUE THREAD

**Issue by sciencepeak** [YingMa1993/CARD#30]
Hi Ying,

We are using the CARDfree for our project. There is an error possibly related to the Rcpp function CARDfree(). I have attached the code, error, and rds object. Could you please help debug?

# Code

```r
CARDfree_obj = createCARDfreeObject(
    markerList = markerList,
    spatial_count = current_expression_Matrix,
    spatial_location = current_position_dataframe,
    minCountGene = 100,
    minCountSpot = 5)
saveRDS(CARDfree_obj, file = "CARDfree_obj.rds")
result_CARDfree_obj = CARD_refFree(CARDfree_obj)
```

# Error message

```r
## Number of unique marker genes: 1711 for 20 cell types ...
Error in ResList[[Optimal]] : 
  attempt to select less than one element in get1index
```

# rds file

The file is 54MB, bigger than the GitHuB file size limit 25MB, so I upload it to the dropbox [here](https://www.dropbox.com/s/69w475n8sbnd8ku/CARDfree_obj.rds?dl=0). There is no need to register the dropbox account.

Thank you very much.

**Comment by dcipurko** [comment]
Not sure this is exactly related to your problem, but I had the same error when the row names of my spatial_location dataframe did not match my count matrix. In my case, R was mishandling assigning the row names when set using the rownames() function, but I fixed this by setting the spatial barcodes as a column then using dplyr's column_to_rownames() function. Might be worth checking this!
