### ISSUE TITLE
Question about single cell resolution mapping on multiple samples

### ISSUE THREAD

**Issue by rohitarorayyc** [YingMa1993/CARD#32]
Dear Ying,

I am in the process of utilizing the single cell resolution mapping feature on Spatial Transcriptomic sections that have been generated using 10x Visium. I am planning to study 12 different sections and I intend to utilize the same single cell reference for all of them. 

I am concerned about the potential for single-cell duplication across my scMapped objects. Specifically, I am worried that when conducting downstream analysis, the same single-cell may appear in multiple of my objects. Is this a valid concern and, if so, what measures might I take to address this problem or avoid it entirely?

**Comment by YingMa0107** [comment]
Hi @Rohitarora21 

Thank you very much for your interest in our package!

Your concern is valid. For the spatial locations that are highly correlated with the same set of single cells in the scRNA-seq reference data, the same single-cell may appear in multiple spatial locations across different sections. In this case, I suggest you to use the scRNA-seq reference with a large number of cells with each cell type also containing a large numbers of cells to avoid repeated mapping at some level. This might also depends on the tissue, if these 12 different sections have heterogenous cell type compositions, the same single cell might not that largely appear in multiple of your subjects.

Best,
Ying
