### ISSUE TITLE
How to choose a dominant cell type in one position of spatial transcriptomics data?

### ISSUE THREAD

**Issue by pillar-github** [YingMa1993/CARD#33]
Hi, thank you so much for this package!
I was wondering if I could define a cell-type name instead of cell-type proportion for one point of spatial transcriptomics data, such as Stereo-seq or MERFISH, with the single-cell resolution. And in my opinion, whether the cell type with the highest proportion is the dominant cell type? Thanks again for your work on this!

**Comment by YingMa0107** [comment]
Hi @pillar-github, 

Thank you very much for your interest in our package! 

Based on your question, for the high-resolution data such as Stereo-seq or MERFISH, you can use the cell type with the highest proportion as a dominant cell type. For those spatial locations where several cell types have the similar proportions, you probably need to be careful with using the highest proportion as the dominant cell type.

**Comment by pillar-github** [comment]
Thanks a lot for your suggestion! 

About the extension of CARD for reference-free deconvolution (CARDfree), the inferred cell types do not come with the cell type label in the "markerList". Would you give us some suggestions to determine the order of "CT*x" for matching with the cell types in the "markerList" if we don't have the original results of CARD?

Thanks again for your suggestions!

**Comment by YingMa0107** [comment]
Hi @pillar-github, 

Thanks for sharing the details!

Here are some of my suggestions: 

1. probably you can visualize the spatial gene expression pattern of the marker genes in your input list, and to see if the pattern is highly consistent with the spatial distribution of a specific cell type proportion. You can also calculate the correlation between the marker gene expression and the cell type proportion. It is expected that the marker gene's expression should be higher with its corresponding cell type proportion than that of the non-marker genes. 

2. Probably you can also perform some downstream analysis to annotate the CT*x label. The basic idea is to link the cell type with the highest cell type specific expression among the marker genes to the corresponding cell type. For example, 

```
### first you extract the CARD estimated cell type specific expression profile in the reference-free version
B = CARD_obj@algorithm_matrix$B
### Take the marker genes belong to the first cell type in your markerList as an example
genes = markerList[[1]]
### remain the genes that are shown in the B matrix
B_sub = B[rownames(B) %in% genes,]
### check which CT*x has the highest expression among these marker genes
### check the median: we expected that the CT*x column with the highest median expression among these marker genes should be labeled with the cell type corresponding to these marker genes
CTIndex = which(colMeans(B_sub) == max(colMeans(B_sub)))
### or check the frequency that has the highest expression among the marker genes
CTIndex = max(apply(B_sub,1, which.max))
```

Then you can iterate your input marker gene list. Please be careful these are just simple suggestions, if there are several cell types highly correlated with each other, it might be difficult to map each cell type successfully especially the number of cell types is also large here (we have discussed this in the Discussion in our paper). Let me know if these do not make sense to you. 


Best,
Ying

**Comment by pillar-github** [comment]
Thanks for your patient reply! 

I think that your suggestions will make sense to my work. Later, I will test other methods to identify cell types in my spatial transcriptomics data (generated from 10X Xenium and Stereo-seq).
