### ISSUE TITLE
statistic inference in Cpp

### ISSUE THREAD

**Issue by hzaurzli** [YingMa1993/CARD#35]
Hi ying:
  I'm David Runze Li,congratulations for your work published on NBT, I have learned more, actually i staill have some questions to ask, if you can give me some advices:
1. in paper supplementary page 121-122 formula 9 and page 122-123 formula 10,you develop new way to estimate matrix V log(pr) and Q,i think this 2 formulas are same especially in statistic, one is to estimate maximum, another one is to estimate minimum., but in your Rcpp line 104-109, i just wonder in this script why you ignore ```K/2*log(det(L))```?

**Comment by YingMa0107** [comment]
Hi @hzaurzli, 

Thank you for your question and your interest in our work.
 
Regarding the two formulas in the supplementary file: 
1)    Maximizing the term logPr() in equation (9) is equivalent to minimizing the term Q in equation (10), as the latter takes the negative sign of the former. 

2)   The following optimization procedures from equations (11) to (17) for V, b_k, lambda_k, and sigma_e2, they are all not dependent on the K/2log(det(L)) term. Therefore, calculating the K/2log(det(L)) or not will not affect the iterating updating procedures on all these parameters. Additionally, calculating K/2log(det(L)) can be computationally challenging, especially for a large L matrix with dimensions of more than 10,000 * 10,000. This may not be feasible for high-resolution spatial transcriptomics data such as Slide-seq or Slide-seq2 data (It might take several hours and/or generate some memory errors). However, excluding this term does not affect the estimation of all parameters. Compared to the other parts of the cost function related to the parameters we want to optimize, the K/2log(det(L)) term has little influence on the overall scale of the Q function. Therefore, I did not specifically include it in my Rcpp code.

Hope this is helpful! 
 
Best regards,
Ying
