### ISSUE TITLE
Error in running CARDref()

### ISSUE THREAD

**Issue by RealBrainWang** [YingMa1993/CARD#36]
Dear Professor:
I am very interested in the function of CARD's cell type deconvolution, after reading your article. However, when I tried to run CARD with tutorial dataset, the CARDref() function encountered an error.
Everything runs normally, including the createCARDObject function, until the CARD_deconvolution function. The following information appears here:

#########
## Deconvolution Starts! ...
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
Error in CARDref(XinputIn = as.matrix(Xinput_norm), UIn = as.matrix(B),  : 
  could not found object '_CARD_CARDref'
#########

Finally, I found that there was a problem in step CARDref(). The input data of CARDref() including XinputIn, UIn, WIn, phiIn, max_iterIn, epsilonIn, initV, initb, initSigma_e2 and initLambda are complete. I will be very grateful if you have any way to solve this problem and inform me.

**Comment by YingMa0107** [comment]
Hi @YaobangWang, 

Thank you for your interest in our package! Could you please provide me more information about the environment that you are using, i.e. SessionInfo() in R. 

To help me better solve your problem, would it be possible for you to share your CARD_obj with me? Usually, users can run the tutorial successfully, I've also tested it suceessfully in both Linux, MacOS and Windows system. So it would be better for me to take a look at your CARD_obj to see what's going on. 

Thank you!

P.S. Please call me Ying.

**Comment by RealBrainWang** [comment]
[CARD_obj.zip](https://github.com/YingMa0107/CARD/files/10947485/CARD_obj.zip)
Hi Ying
The environment information of R and CARD_obj generated with tutorial dataset have been uploaded. If you have any other requirements, please don't hesitate to contact me.

**Comment by RealBrainWang** [comment]
> Hi @YaobangWang,
> 
> Thank you for your interest in our package! Could you please provide me more information about the environment that you are using, i.e. SessionInfo() in R.
> 
> To help me better solve your problem, would it be possible for you to share your CARD_obj with me? Usually, users can run the tutorial successfully, I've also tested it suceessfully in both Linux, MacOS and Windows system. So it would be better for me to take a look at your CARD_obj to see what's going on.
> 
> Thank you!
> 
> P.S. Please call me Ying.
[CARD_obj.zip](https://github.com/YingMa0107/CARD/files/10979168/CARD_obj.zip)

Hi Ying
The environment information of R and CARD_obj generated with tutorial dataset have been uploaded. If you have any other requirements, please don't hesitate to contact me.

**Comment by YingMa0107** [comment]
Hi @YaobangWang,

I've tried the tutorial on your created CARD_obj on my computer, it seems that it can be finished without any errors. So I'm still trying to find a Windows system to reproduce your error. Based on the error message, it seems that the error comes from the Rcpp part, I'm wondering whether you could successfully compile the cpp function in your R environment? Can you run sourceCpp("./CARD/src/CARDref.cpp") successfully without any errors? Thanks!

Best,
Ying
