### ISSUE TITLE
borders for each dot 

### ISSUE THREAD

**Issue by LooLipin** [YingMa1993/CARD#37]
Thanks for much for the package. I have a very basic question regarding the plot.

Specifically for CARD.vizualize.prop, I would like to add a scale for the scores. How do I do that?

Thanks,
Lipin

**Comment by LooLipin** [comment]
All good, I figured it out by adding geompoint(pch=21) within the function

**Comment by LooLipin** [comment]
Please ignore my issue, I have figured it out.

**Comment by YingMa0107** [comment]
Hi @LooLipin,

I'm glad to hear that you have figured it out. For all the modifications on the plot, you can always add some arguments within the ggplot related functions. 

Best,
Ying
