### ISSUE TITLE
Question about PDAC data provided in tutorial

### ISSUE THREAD

**Issue by AnthonyX1an** [YingMa1993/CARD#43]
Hi！
I read CARD paper and find a lot of comparison between CARD and other method, so I want to use PDAC data provided in tutorial in RCTD method. But when I create a RCTD object I get an error: 'need a minimum of 25 cells for each cell type in the reference.'
Could you please give me some advice about how to solve this problem?

**Comment by YingMa0107** [comment]
Hi @AnthonyX1an, 

Thank you for your interest in our package!

The version of RCTD I used has an argument in their creat.RCTD() function to control the number of cells in each cell type. Specifically, I set `myRCTD <- create.RCTD(puck, reference, max_cores = 5,CELL_MIN = 1)`. I also checked their latest GitHub, they may have updated their package for several times, now you need to set the argument CELL_MIN_INSTANCE = 1 to control the minimal number of cells in each cell type in their updated create.RCTD() function. Hope this helps!

Best,
Ying
