### ISSUE TITLE
The weight of genes in different clusters

### ISSUE THREAD

**Issue by Qirongmao97** [YingMa1993/CARD#45]
Hi, thanks for creating CARD! The tool is very amazing

Just wondering if it is possible to check the weight of marker genes for deconvoluting clusters in space.

**Comment by YingMa0107** [comment]
Hi @Qirongmao97, 

We appreciate your interest in our CARD package!

Currently, CARD is built upon the non-negative matrix factorization. Specifically, we implemented two versions, the marker gene list is only utilized in the reference-free version of CARD, CARDfree. However, the current version might not be able to extract the weight of marker genes. But you might be able to check some weighted least square based framework to see if you can extract the weight for these marker genes. 

Hope this helps!

Best,
Ying
