### ISSUE TITLE
Empty figure content when I run CARD.visualize.pie in R to generate a spatial pie plot 

### ISSUE THREAD

**Issue by krigia** [YingMa1993/CARD#47]
Hello,

I am running the function CARD.visualize.pie in R to generate a pie spatial plot for 10X Visium data. 
However, I get an empty figure which is likely due to the number of spots (>400).
Is there any way to fix this issue and visualize the data in a spatial pie plot?
Other deconvolution tools like DWLS allow to visualize Visium data in a pie spatial plot.
Thank you.

**Comment by YingMa0107** [comment]
Hi @krigia,

Thank you for your interest in CARD! 

I have updated the code as previously the radius parameter might not be correctly set for all settings.

Now you can reinstall the CARD package or just source the updated CARD.visualize.pie() function. In the updated code, I added options for the users to set the radius parameter by themself and also added more default colors. If you don't want to provide the radius or colors by yourself, you can also leave these two arguments to be NULL, then the function will automatically set them. 

You can still run the following code to plot it: 

```
p1 <- CARD.visualize.pie(
	proportion = CARD_obj@Proportion_CARD,
	spatial_location = CARD_obj@spatial_location)
```

Please try the updated function and let me know if it can produce the scatter pie plot successfully. 


Best,
Ying
