### ISSUE TITLE
Does CARD work using normalized (no raw) spatial and scRNA-seq count data?

### ISSUE THREAD

**Issue by krigia** [YingMa1993/CARD#48]
Hello @YingMa0107 

I ran the CARD deconvolution analyses using filtered spatial and  scRNA-seq count data.
The spatial data were raw, however the scRNA-seq data I used were already normalized.
Does CARD work for normalized/scale data or you suggest to use only raw count data?
Thank you.

**Comment by YingMa0107** [comment]
Hi @krigia, 

Thank you for your question!

Please see my answer from a previous similar post [Issue #44 ]


Best,
Ying
