### ISSUE TITLE
Score the gene set

### ISSUE THREAD

**Issue by 1JYL123** [YingMa1993/CARD#49]
Hello @YingMa0107,
Thanks for creating CARD! The tool is very useful, it helps me a lot.
Now I have a gene list, I want to score the each gene in this gene list and map the scores into spatial transcriptomic pictures(like the "AddMouduleScore()" function in Seurat),but I can't find this function in CARD.

**Comment by YingMa0107** [comment]
Hi @1JYL123,

I'm glad to hear that you find CARD useful. As for your question about scoring genes and mapping the scores onto spatial transcriptomic pictures, currently, CARD doesn't have a built-in function similar to "AddModuleScore()" in Seurat. CARD focuses on the deconvolution analysis of spatial transcriptomics data, so the specific functionality you mentioned is not available at the moment. However, we appreciate your feedback, and we may consider adding such a feature in future updates based on user demand.

If you have any further questions or need assistance with other aspects of CARD, feel free to reach out. 

Best,
Ying

**Comment by 1JYL123** [comment]
> Hi @1JYL123,
> 
> I'm glad to hear that you find CARD useful. As for your question about scoring genes and mapping the scores onto spatial transcriptomic pictures, currently, CARD doesn't have a built-in function similar to "AddModuleScore()" in Seurat. CARD focuses on the deconvolution analysis of spatial transcriptomics data, so the specific functionality you mentioned is not available at the moment. However, we appreciate your feedback, and we may consider adding such a feature in future updates based on user demand.
> 
> If you have any further questions or need assistance with other aspects of CARD, feel free to reach out.
> 
> Best, Ying

Thank you for your sincere reply.
