### ISSUE TITLE
Cannot Install CARD

### ISSUE THREAD

**Issue by gucascau** [YingMa1993/CARD#55]
Hi Ying,

I am trying to install CARD in mac but kept to come across with these errors, Coud you please have a look and give some suggestions?

Thank you!

─  installing *source* package ‘CARD’ ...
   ** using staged installation
   ** libs
   using C++ compiler: ‘clang version 14.0.6’
   using C++11
   using SDK: ‘’
   clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/XXW004/Library/R/arm64/4.3/library/Rcpp/include' -I'/Users/XXW004/Library/R/arm64/4.3/library/RcppArmadillo/include' -I/opt/R/arm64/include     -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -c CARDfree.cpp -o CARDfree.o
   clang-14: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
   CARDfree.cpp:1:10: fatal error: 'iostream' file not found
   #include <iostream>
            ^~~~~~~~~~
   1 error generated.
   make: *** [/Library/Frameworks/R.framework/Resources/etc/Makeconf:198: CARDfree.o] Error 1
   ERROR: compilation failed for package ‘CARD’

Here are some session details
─ Session info ─────────────────────────────────────────────────────────────────────────────────────
 version  R version 4.3.1 (2023-06-16)
 os       macOS Ventura 13.5
 system   aarch64, darwin20
 rstudio  2023.06.1+524 Mountain Hydrangea (desktop)

**Comment by YingMa0107** [comment]
Hi @gucascau,

Thank you for your interest in our package! 

The error message you're encountering is fatal error: 'iostream' file not found, which indicates that the compiler is unable to find the iostream header file, a core component of the C++ standard library.

The warning message clang-14: warning: include path for libstdc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found] is also important, suggesting that you might need to specify the standard library to use with a compiler flag.

Here are steps and suggestions you can take to try to resolve this issue:

1. Update Command Line Tools: Make sure that the Xcode command line tools are installed and up-to-date. You can install/update them by running this in terminal: `xcode-select --install`

2. Specify the Standard Library: 
Add the following line to ~/.R/Makevars: `CXXFLAGS += -stdlib=libc++`

Hope this helps!

Best,
Ying

**Comment by dp9090** [comment]
Hi, 
I have the following error when trying to do CARD_deconvolution. Mainly has to do with the dependencies.
Is there a way to override this?

> CARD_obj = CARD_deconvolution(CARD_object = CARD_obj)
## create reference matrix from scRNASeq...
Error in library(MuSiC) : there is no package called ‘MuSiC’

devtools::install_github('xuranw/MuSiC')
I've already tried with the argument force=TRUE, but still encountered the error below.

ERROR: dependency 'TOAST' is not available for package 'MuSiC'
* removing 'C:/Users/XL/AppData/Local/R/win-library/4.2/MuSiC'
Warning messages:
  1: package ‘TOAST’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 
2: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\XL\AppData\Local\R\win-library\4.2\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\XL\AppData\Local\R\win-library\4.2\rlang\libs\x64\rlang.dll: Permission denied
3: In file.copy(savedcopy, lib, recursive = TRUE) :
  problem copying C:\Users\XL\AppData\Local\R\win-library\4.2\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\XL\AppData\Local\R\win-library\4.2\vctrs\libs\x64\vctrs.dll: Permission denied
4: In i.p(...) :
  installation of package ‘C:/Users/XL/AppData/Local/Temp/Rtmp4sW50E/file5e0c30c6167/MuSiC_1.0.0.tar.gz’ had non-zero exit status

─ Session info ─
R version 4.2.3 (2023-03-15 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)

**Comment by zhangms1709** [comment]
Hi, 
I was able to resolve the dependencies issue you are having by manually installing the two relevant packages in a specific order using [BiocManager](https://cran.r-project.org/web/packages/BiocManager/vignettes/BiocManager.html#installing-biocmanager) and devtools. Hope this helps!
```
BiocManager::install("TOAST")
devtools::install_github('xuranw/MuSiC')
```

> Hi, I have the following error when trying to do CARD_deconvolution. Mainly has to do with the dependencies. Is there a way to override this?
> 
> > CARD_obj = CARD_deconvolution(CARD_object = CARD_obj)
> 
> ## create reference matrix from scRNASeq...
> Error in library(MuSiC) : there is no package called ‘MuSiC’
> 
> devtools::install_github('xuranw/MuSiC') I've already tried with the argument force=TRUE, but still encountered the error below.
> 
> ERROR: dependency 'TOAST' is not available for package 'MuSiC'
> 
> * removing 'C:/Users/XL/AppData/Local/R/win-library/4.2/MuSiC'
>   Warning messages:
>   1: package ‘TOAST’ is not available for this version of R
> 
> A version of this package for your version of R might be available elsewhere, see the ideas at https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages 2: In file.copy(savedcopy, lib, recursive = TRUE) : problem copying C:\Users\XL\AppData\Local\R\win-library\4.2\00LOCK\rlang\libs\x64\rlang.dll to C:\Users\XL\AppData\Local\R\win-library\4.2\rlang\libs\x64\rlang.dll: Permission denied 3: In file.copy(savedcopy, lib, recursive = TRUE) : problem copying C:\Users\XL\AppData\Local\R\win-library\4.2\00LOCK\vctrs\libs\x64\vctrs.dll to C:\Users\XL\AppData\Local\R\win-library\4.2\vctrs\libs\x64\vctrs.dll: Permission denied 4: In i.p(...) : installation of package ‘C:/Users/XL/AppData/Local/Temp/Rtmp4sW50E/file5e0c30c6167/MuSiC_1.0.0.tar.gz’ had non-zero exit status
> 
> ─ Session info ─ R version 4.2.3 (2023-03-15 ucrt) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 10 x64 (build 19044)
