### ISSUE TITLE
How to keep all the  Spatial data?

### ISSUE THREAD

**Issue by Smilenone** [YingMa1993/CARD#56]
When running CARD, there are some of the pixels removed. How to keep the Spatial data?

**Comment by YingMa0107** [comment]
Hi @Smilenone, 

Thank you for your interest in our package. 

You can try to set the minCountGene = 0 when you create the CARD object, then it should keep all the spatial locations. 


Best,
Ying

**Comment by cynthier** [comment]
@YingMa0107 
Hi, Ying, I set       
```
minCountGene = 0,
minCountSpot = 0
```
but after creating object, 200~300 spots will be removed.

**Comment by YMalab** [comment]
@cynthier

This could be due to CARD taking into account the common genes between scRNA-seq and SRT data, and removing the spots if there is no expression across all those common genes.

Best,
Ying
