### ISSUE TITLE
inconsistency with DWLS vs. CARDS deconvolution

### ISSUE THREAD

**Issue by chrkuo** [YingMa1993/CARD#58]
I've noticed some inconsistency between CARDS deconvolution vs. DWLS giotto. Is there a reason why since it seems like the discrepancy should be minimal

**Comment by YMalab** [comment]
Hi @chrkuo,

The observed inconsistency may stem from a variety of factors, including the method itself. For example in the benchmarking studies, such as the one published in Nature Communications (https://www.nature.com/articles/s41467-023-37168-7) and a lot of other papers, the performance of different methods can vary significantly.

Best,
Ying
