### ISSUE TITLE
Simulation code

### ISSUE THREAD

**Issue by lzygenomics** [YingMa1993/CARD#6]
Dear @YingMa0107 ,

Thanks for your nice work~  I wonder if you could share the simulation code~?
I think the simulation method you provided is really fascinating !

Best wishes!

**Comment by YingMa0107** [comment]
Hi @lzygenomics, 

Thank you for your interest in our work! 

I have uploaded the code for simulating the spatially resolved data [here](https://github.com/YingMa0107/CARD-Analysis/tree/master/simulations). I also deposited the simulated data that I generated in the paper [here](https://drive.google.com/drive/folders/18vSET90a3_cvcOwLdyc2beqlM6gJxZwX). Hope this helps!

**Comment by lzygenomics** [comment]
Thanks for your patient reply ! It's really nice 👍
