### ISSUE TITLE
Is it possible to install it with conda?

### ISSUE THREAD

**Issue by ghost** [YingMa1993/CARD#66]
Is it possible to install it with conda? Or enter R in the conda environment to install?
Thanks!

**Comment by YMalab** [comment]
Hi @zhiyafan,

Thank you for your interest in our CARD package!

We haven’t attempted installation via conda. Have you tried installing it using 'devtools', as per our installation guidelines?

Best,
Ying

**Comment by Ray569743422** [comment]
Install devtools with conda and then CARD in R is a feasible way.

**Comment by YMalab** [comment]
@Ray569743422, I appreciate your comment!

**Comment by ghost** [comment]
> Install devtools with conda and then CARD in R is a feasible way.

It works! Thanks!
