### ISSUE TITLE
Error in CARD installation in MacOS

### ISSUE THREAD

**Issue by krigia** [YingMa1993/CARD#67]
Hello CARD team @YingMa0107 @YMalab 
I am getting the following error while I try to install CARD package in Rstudio ( R version 4.2 and 4.3).

_ERROR: package installation failed Error: Failed to install 'CARD' from GitHub:   ! System command 'R' failed In addition: Warning message: In i.p(...) :   installation of package ‘RcppArmadillo’ had non-zero exit status_

**I tried to installed RcppArmadillo package, homebrew and gfortran. Although they are installed, still the problem is not fixed:** **Please see below:**

> remotes::install_github("YMa-lab/CARD")

Downloading GitHub repo YMa-lab/CARD@HEAD
Skipping 3 packages not available: Biobase, SummarizedExperiment, SingleCellExperiment
── R CMD build ─────────────────────────────────────────────────────────────────
   checking for file ‘/private/var/folders/r_/ddb8mb3d0rz13_3mss2sjgz00000gr/T/R✔  checking for file ‘/private/var/folders/r_/ddb8mb3d0rz13_3mss2sjgz00000gr/T/Rtmpx3ukVU/remotesb1f2b1f1a4e/YMa-lab-CARD-2d64b91/DESCRIPTION’
─  preparing ‘CARD’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages
         -----------------------------------
─  installing *source* package ‘CARD’ ...
   ** using staged installation
   ** libs
   using C++ compiler: ‘Apple clang version 14.0.3 (clang-1403.0.22.14.1)’
   using C++11
   using SDK: ‘’
   clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/kgiannikou/Library/R/arm64/4.3/library/Rcpp/include' -I'/Users/kgiannikou/Library/R/arm64/4.3/library/RcppArmadillo/include' -I/opt/R/arm64/include     -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c CARDfree.cpp -o CARDfree.o
   clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/kgiannikou/Library/R/arm64/4.3/library/Rcpp/include' -I'/Users/kgiannikou/Library/R/arm64/4.3/library/RcppArmadillo/include' -I/opt/R/arm64/include     -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c CARDref.cpp -o CARDref.o
   clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/kgiannikou/Library/R/arm64/4.3/library/Rcpp/include' -I'/Users/kgiannikou/Library/R/arm64/4.3/library/RcppArmadillo/include' -I/opt/R/arm64/include     -fPIC  -falign-functions=64 -Wall -g -O2  -Wall -pedantic -fdiagnostics-color=always -c RcppExports.cpp -o RcppExports.o
   clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o CARD.so CARDfree.o CARDref.o RcppExports.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
   **ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0'
   ld: warning: directory not found for option '-L/opt/gfortran/lib'
   ld: library not found for -lgfortran
   clang: error: linker command failed with exit code 1 (use -v to see invocation)
   make: *** [CARD.so] Error 1
   ERROR: compilation failed for package ‘CARD’
─  removing ‘/private/var/folders/r_/ddb8mb3d0rz13_3mss2sjgz00000gr/T/RtmpSo46vj/Rinstb2292b012d8e/CARD’**
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'CARD' from GitHub:
  ! System command 'R' failed_

I would greatly appreciate your help.

Thank you

**Comment by krigia** [comment]
@YingMa0107 @YMalab I created a personal token as required but I am still getting the same error as above.
Please advise. Thank you

**Comment by YMalab** [comment]
Hi @krigia,

Thank you for your interest in our package. 

The problem is because you don't have gfortran installed. Previously, I followed this to install CARD on a relatively new MacBook M2 system. Hope this helps.

```
1. install brew:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

2. export PATH:
export PATH="/opt/homebrew/bin:$PATH"

3. source .zshrc, your case might be souce ~/.bashrc
either source ~/.zshrc or source ~/.bashrc

4. install gcc:
brew install

5. check your gcc version, mine is 13, so ****/gcc/13, replace your own version number
export FLIBS="-L/opt/homebrew/lib/gcc/13 -lgfortran -lquadmath -lm"

6. check gfortran version:
gfortran --version

7. check if gfortran exists:
find /opt/homebrew -name libgfortran.a

8. make a ~/.R foilder and modify MakeVars
mkdir -p ~/.R
vim ~/.R/Makevars
FLIBS=-L/opt/homebrew/lib/gcc/13 -lgfortran -lquadmath -lm
```

**Comment by krigia** [comment]
@YMalab Thank you for your respond. I have installed gfortran successfully. this is not a problem.
However, will follow your instructions above and see what I get. Thank you.

**Comment by krigia** [comment]
@YMalab @YingMa0107 

THANK YOU. I am getting multiple warnings.

Warning: replacing previous import ‘RcppML::nmf’ by ‘NMF::nmf’ when loading ‘CARD’
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Warning: replacing previous import ‘RcppML::nmf’ by ‘NMF::nmf’ when loading ‘CARD’
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
Warning: replacing previous import ‘RcppML::nmf’ by ‘NMF::nmf’ when loading ‘CARD’
** testing if installed package keeps a record of temporary installation path
* DONE (CARD)
> # load package
> library(CARD)
Registered S3 methods overwritten by 'registry':
  method               from
  print.registry_field proxy
  print.registry_entry proxy
Warning message:
replacing previous import ‘RcppML::nmf’ by ‘NMF::nmf’ when loading ‘CARD’


How can this affect the CARD downstream analysis? To sure where exactly to replace previous import ‘RcppML::nmf’ by ‘NMF::nmf’ when loading ‘CARD’. Please advise. Thank you.

**Comment by krigia** [comment]
@YingMa0107 @YMalab  issue solved. Thank you

**Comment by lobster-llx** [comment]
Thank you,I also solved this issue.
