### ISSUE TITLE
Cannot change colours in CARD.visualize.Cor

### ISSUE THREAD

**Issue by michaeljpitcher** [YingMa1993/CARD#7]
Hi,

The colours in CARD.visualize.Cor seem to be hard-coded and don't allow the user to change them. Also, the param text suggests the default colours are ("lightblue","lightyellow","red") but they seem to be red, white and green.

**Comment by YingMa0107** [comment]
Hi @michaeljpitcher, 

Sorry for this! I previously forgot to remove the color line when I wrapped up the function! Thank you for raising the issue! I have updated the corresponding visualization function and now you can use your own defined colors in the CARD.visualize.Cor function. 

Let me know if this solves the issue or if I can help you further with this!

**Comment by michaeljpitcher** [comment]
That solved it, thanks.
